package model

import model.MovableEntity;
import model.Cavalry;
import model.Fortress;

rule "outOfCom"
	agenda-group "Battle"
	when
		$m : MovableEntity(isConnected() == false) 
	then
		$m.setAttack(0);
		$m.setAllyDefence(0);
		$m.setDefence(0);
end

rule "bonusFortress"
	agenda-group "Battle"
	when
		$b : Board()
		$m : MovableEntity(isConnected() == true, $coord : coord)
	then
		if($b.isFortress($coord.x, $coord.y) && !($m instanceof Cavalry))
			$m.setDefence($m.getDefence() + Fortress.FORTRESS_BONUS);
		
end

rule "bonusMountainPass"
	agenda-group "Battle"
	when
		$b : Board()
		$m : MovableEntity(isConnected() == true, $coord : coord)
	then
		if($b.isMountainPass($coord.x, $coord.y) && !($m instanceof Cavalry))
			$m.setDefence($m.getDefence() + MountainPass.MOUNTAIN_PASS_BONUS);
		
end

rule "canBeKilled"
	agenda-group "Battle"
	when 
		$m : MovableEntity($coord : coord)
	then
		if($m.getAllyDefence() < $m.getEnemyAttack())
			$m.setCanBeKilled(true);
		if($m.getAllyDefence() == $m.getEnemyAttack())
			$m.setMustRetreat(true);
end
