package model

import model.MovableEntity;
import model.Fighter;
import model.Cavalry;
import model.Fortress;

rule "outOfCom"
	agenda-group "Battle"
	when
		$f : Fighter(isConnected() == false, $coord : coord) 
	then
		$f.setAttackNull();
		$f.setAllyDefence(0);
		$f.setDefence(0);
end

rule "bonusFortress"
	agenda-group "Battle"
	when
		$b : Board()
		$f : Fighter(isConnected() == true, $coord : coord)
	then
		if($b.isFortress($coord.x, $coord.y) && !($f instanceof Cavalry))
			$f.setDefence($f.getDefence() + Fortress.FORTRESS_BONUS);
		
end

rule "bonusMountainPass"
	agenda-group "Battle"
	when
		$b : Board()
		$f : Fighter(isConnected() == true, $coord : coord)
	then
		if($b.isMountainPass($coord.x, $coord.y) && !($f instanceof Cavalry))
			$f.setDefence($f.getDefence() + MountainPass.MOUNTAIN_PASS_BONUS);
		
end

