package model

import main.Board;
import model.Arsenal;
import model.Fighter;
import model.Relay;
import model.SwiftRelay;


// Deplacer les getNbrInstances dans les then
rule "Team0WithoutArsenal"
	agenda-group "Win"
	no-loop
    when
    	$b : Board()
    then
    	if ($b.getNbrInstances(Arsenal.class, 0) == 0){
    		System.out.println("Winner 1 / Team0WithoutArsenal");
    		$b.setWinner(1);
    	}
end

rule "Team1WithoutArsenal"
	agenda-group "Win"
	no-loop
    when
    	$b : Board()
    then
    	if ($b.getNbrInstances(Arsenal.class, 1) == 0){
    		System.out.println("Winner 0 / Team1WithoutArsenal");
    		$b.setWinner(0);
    	}
end
 
rule "Team0WithoutFighter"
	agenda-group "Win"
	no-loop
    when
    	$b : Board()
    then
    	if ($b.getNbrInstances(Fighter.class, 0) == 0) {
    		System.out.println("Winner 1 / Team0WithoutFigther");
    		$b.setWinner(1);
    	}
end

rule "Team1WithoutFighter"
	agenda-group "Win"
	no-loop
    when
    	$b : Board()
    then
    	if ($b.getNbrInstances(Fighter.class, 1) == 0) {
    		$b.setWinner(0);
    		System.out.println("Winner 0 / Team1WithoutFigther");
    	}
end

rule "Team0WithoutRelay"
	agenda-group "Win"
	no-loop
    when
    	$b : Board()
    then
    	if ($b.getNbFighterConnected(0) == 0 && $b.getNbrInstances(Relay.class, 0) == 0 && $b.getNbrInstances(SwiftRelay.class, 0) == 0) {
    		$b.setWinner(1);
    		System.out.println("Winner 1 / Team0WithoutRelay");
    	}
end

rule "Team1WithoutRelay"
	agenda-group "Win"
	no-loop
    when
    	$b : Board()
    then
   		if ($b.getNbFighterConnected(1) == 0 && $b.getNbrInstances(Relay.class, 1) == 0 && $b.getNbrInstances(SwiftRelay.class, 1) == 0 ) { 
   			$b.setWinner(0);
   			System.out.println("Winner 0 / Team1WithoutRelay");
   		}
end
 

