package model

import main.Board;
import model.Arsenal;
import model.Fighter;
import model.Relay;
import model.SwiftRelay;


// Deplacer les getNbrInstances dans les then
rule "Team0WithoutArsenal"
	agenda-group "Win"
	no-loop
    when
    	$b : Board( isMapLoaded(), getNbrInstances(Arsenal.class, 0) == 0 )
    then
    	System.out.println("Win because : Team0WithoutArsenal");
    	//if ($b.getNbrInstances(Arsenal.class, 0) == 0)
    		$b.setWinner(1);
end

rule "Team1WithoutArsenal"
	agenda-group "Win"
	no-loop
    when
    	$b : Board( isMapLoaded(), getNbrInstances(Arsenal.class, 1) == 0 )
    then
    	System.out.println("Win because : Team1WithoutArsenal");
    	//if ($b.getNbrInstances(Arsenal.class, 1) == 0)
    		$b.setWinner(0);
end
 
rule "Team0WithoutFighter"
	agenda-group "Win"
	no-loop
    when
    	$b : Board( isMapLoaded(), getNbrInstances(Fighter.class, 0) == 0 )
    then
    	System.out.println("Win because : Team0WithoutFighter");
    	//if ($b.getNbrInstances(Fighter.class, 0) == 0)
    		$b.setWinner(1);
end

rule "Team1WithoutFighter"
	agenda-group "Win"
	no-loop
    when
    	$b : Board( isMapLoaded(), getNbrInstances(Fighter.class, 1) == 0 )
    then
    	System.out.println("Win because : Team1WithoutFighter");
    	//if ($b.getNbrInstances(Fighter.class, 1) == 0)
    		$b.setWinner(0);
end

rule "Team0WithoutRelay"
	agenda-group "Win"
	no-loop
    when
    	$b : Board( isMapLoaded(), getNbFighterConnected(0) == 0 && getNbrInstances(Relay.class, 0) == 0 && getNbrInstances(SwiftRelay.class, 0) == 0 )
    then
    	System.out.println("Win because : Team0WithoutRelay");
    	//if ($b.getNbFighterConnected(0) == 0 && $b.getNbrInstances(Relay.class, 0) == 0 && $b.getNbrInstances(SwiftRelay.class, 0) == 0)
    		$b.setWinner(1);
end

rule "Team1WithoutRelay"
	agenda-group "Win"
	no-loop
    when
    	$b : Board( isMapLoaded(), getNbFighterConnected(1) == 0 && getNbrInstances(Relay.class, 1) == 0 && getNbrInstances(SwiftRelay.class, 1) == 0 )
    then
    	System.out.println("Win because : Team1WithoutRelay");
   		//if ($b.getNbFighterConnected(1) == 0 && $b.getNbrInstances(Relay.class, 1) == 0 && $b.getNbrInstances(SwiftRelay.class, 1) == 0 )
   			$b.setWinner(0);
end
 

